@startuml UserManage2
hide footbox

actor User as "Quản trị viên"
boundary ListPage as "Trang danh sách"
boundary DetailsPage as "Trang chi tiết"
boundary CreateUpdatePage as "Trang tạo/sửa"
control API as "API\nNgười dùng"
database Database as "CSDL\nNgười dùng"

group Tạo / sửa
    alt Tạo
        User -> ListPage ++ : Bấm 'Tạo'
        ListPage -> CreateUpdatePage --++ : Tạo dữ liệu mới
        CreateUpdatePage --> User -- : Hiện trang
        |||
    else Sửa
        User -> DetailsPage ++ : Truy cập
        DetailsPage --> User -- : Hiện trang
        User -> DetailsPage ++ : Chọn nút 'Sửa'
        DetailsPage -> CreateUpdatePage --++ : Điền thông tin\ncó sẵn
        CreateUpdatePage --> User -- : Hiện trang
        |||
    end

    User -> CreateUpdatePage ++ : Điền thông tin và Chọn nút 'Lưu'
    CreateUpdatePage -> API ++ : Gửi yêu cầu
    API -> Database ++ : Tạo/sửa dữ liệu
    Database --> API -- : Trả về kết quả
    API --> CreateUpdatePage -- : Gửi phản hồi
    CreateUpdatePage --> DetailsPage --++ : Truy cập
    DetailsPage --> User -- : Hiện trang
    |||
end

group Xóa
    User -> DetailsPage ++ : Truy cập
    DetailsPage --> User -- : Hiện trang
    User -> DetailsPage ++ : Chọn nút 'Xóa'
    DetailsPage -> API ++ : Gửi yêu cầu
    API -> Database ++ : Xóa dữ liệu
    Database --> API -- : Trả về kết quả
    API --> DetailsPage -- : Gửi phản hồi
    DetailsPage --> ListPage --++ : Truy cập
    ListPage --> User -- : Hiện trang
    |||
end

@enduml
