using Domain.DTOs;
using Domain.DTOs.ExportReports;
using Domain.Entities;
using Domain.Mappers;
using MAUIApp.Services.Interfaces;

namespace MAUIApp.Services.Mocks;

public sealed class ExportReportService : IExportReportService
{
	private readonly List<ExportReport> _entities =
	[
		new ExportReport()
		{
			Id = "abm32",
			DateCreated = DateTime.Now - TimeSpan.FromDays(12),
			Author = new UserInfo()
			{
				Id = "1nva",
				Name = "Nguyễn Văn A",
			},
			IsAutoGenerated = false,
			ProductItems =
			[
				new ExportReportProductItem()
				{
					Id = "Avxm1",
					Name = "Thuốc trị",
					Barcode = "02957293735313",
					Quantity = 12,
				},
				new ExportReportProductItem()
				{
					Id = "39dnb",
					Name = "Dược phẩm",
					Barcode = "5432687452164",
					Quantity = 4,
				},
			]
		},
		new ExportReport()
		{
			Id = "6532a",
			DateCreated = DateTime.Now - TimeSpan.FromDays(3),
			DateCancelled = DateTime.Now - TimeSpan.FromDays(1),
			Author = new UserInfo()
			{
				Id = "1nva",
				Name = "Nguyễn Văn A",
			},
			IsAutoGenerated = false,
			ProductItems =
			[
				new ExportReportProductItem()
				{
					Id = "Avxm1",
					Name = "Thuốc trị",
					Barcode = "02957293735313",
					Quantity = 12,
				},
			]
		},
		new ExportReport()
		{
			Id = "13265",
			DateCreated = DateTime.Now - TimeSpan.FromDays(1),
			Author = new UserInfo()
			{
				Id = "1nva",
				Name = "Nguyễn Văn A",
			},
			IsAutoGenerated = true,
			ProductItems =
			[
				new ExportReportProductItem()
				{
					Id = "Avxm1",
					Name = "Thuốc trị",
					Barcode = "02957293735313",
					Quantity = 54,
				},
				new ExportReportProductItem()
				{
					Id = "39dnb",
					Name = "Dược phẩm",
					Barcode = "5432687452164",
					Quantity = 8,
				},
			]
		},
	];

	public Task<ExportReportShort[]> SearchAsync(
		string? productSearch = null,
		OrderBy orderBy = OrderBy.Descending,
		DateTime? dateStart = null,
		DateTime? dateEnd = null,
		ushort pageNumber = 1,
		ushort pageSize = 15)
	{
		var results = _entities.Select(ExportReportMapper.ToShort).ToArray();

		return Task.FromResult(results);
	}

	public Task<ExportReport> GetAsync(string id)
	{
		var result = _entities.First(x => x.Id == id);

		return Task.FromResult(result);
	}

	public Task CreateAsync(ExportReportCreate data)
	{
		return Task.CompletedTask;
	}

	public Task DeleteAsync(string id)
	{
		return Task.CompletedTask;
	}

	public Task CancelAsync(string id)
	{
		return Task.CompletedTask;
	}
}
