@startuml ManageInvoice
left to right direction

actor :Người dùng: as User
actor :Quản lí: as Manager
actor :Nhân viên: as Staff

usecase ManageInvoice as "Quản lý hóa đơn"
usecase CreateInvoice as "Tạo hóa đơn"
usecase MarkPaidInvoice as "Đánh dấu đã\nthanh toán"
usecase ReturnInvoice as "Trả hàng"

Manager --|> User
Staff --|> User

User -- ManageInvoice
ManageInvoice ..> CreateInvoice : <<include>>
ManageInvoice <.. MarkPaidInvoice : <<extend>>
ManageInvoice <.. ReturnInvoice : <<extend>>
@enduml