@startuml General
left to right direction

actor :Người dùng: as User
actor :Quản lý: as Manager
actor :Nhân viên: as Staff

rectangle Product as "Sản phẩm" {

}
rectangle Client as "Khách hàng" {
    
}
rectangle AuditReport as "Báo cáo kiểm kho" {
    
}
rectangle ExportReport as "Báo cáo xuất kho" {
    
}
rectangle ImportReport as "Báo cáo nhập kho" {
    
}
rectangle Invoice as "Hóa đơn" {
    
}

Manager --|> User
Staff --|> User

Manager -- AuditReport
Manager -- ExportReport
Manager -- ImportReport
User -- Client
User -- Product
User -- Invoice
@enduml