@startuml Invoice
left to right direction

actor User as "Người dùng"
actor Manager as "Quản lý"
actor Staff as "Nhân viên"

rectangle Invoice as "Hóa đơn" {
    usecase InvoiceSearch as "Tìm kiếm hóa đơn"
    usecase InvoiceSearchByProductName as "Tìm bằng tên sản phẩm"
    usecase InvoiceSearchByBarcode as "Tìm bằng mã sản phẩm"
    usecase InvoiceSearchByClientName as "Tìm bằng tên khách hàng"
    usecase InvoiceSearchByClientPhonenumber as "Tìm bằng số điện thoại khách hàng"
    usecase InvoiceSearchByStaffName as "Tìm bằng tên nhân viên bán"
    usecase InvoiceFilterStatus as "Lọc trạng thái đơn"
    usecase InvoiceFilterStartDate as "Lọc từ ngày tạo"
    usecase InvoiceFilterEndDate as "Lọc đến ngày tạo"
    usecase InvoiceView as "Xem hóa đơn"
    usecase InvoiceCreate as "Thêm hóa đơn"
    usecase InvoiceDelete as "Xóa hóa đơn"
    usecase InvoiceCancel as "Hủy hóa đơn (Khách trả hàng)"
    usecase InvoicePay as "Đánh dấu hóa đơn đã thanh toán"
    usecase ExportReportCreate as "Tạo báo cáo xuất hàng"
    usecase ProductUpdateStock as "Cập nhật tồn kho sản phẩm"
    usecase ExportReportCancel as "Hủy báo cáo xuất hàng"
}

Manager --|> User
Staff --|> User
User -- InvoiceSearch
User -- InvoiceView
User -- InvoiceCreate
User -- InvoiceDelete
User -- InvoiceCancel
User -- InvoicePay
InvoiceSearch <|-- InvoiceSearchByProductName
InvoiceSearch <|-- InvoiceSearchByBarcode
InvoiceSearch <|-- InvoiceSearchByClientName
InvoiceSearch <|-- InvoiceSearchByClientPhonenumber
InvoiceSearch <|-- InvoiceSearchByStaffName
InvoiceSearch <|-- InvoiceFilterStatus
InvoiceSearch <|-- InvoiceFilterStartDate
InvoiceSearch <|-- InvoiceFilterEndDate
InvoicePay ..> InvoiceCreate : <<extend>
InvoiceCancel ..> ExportReportCancel : <<include>>
ExportReportCancel ..> ProductUpdateStock : <<include>>
InvoiceCreate ..> ExportReportCreate : <<include>>
ExportReportCreate ..> ProductUpdateStock : <<include>>
@enduml