@startuml Product
left to right direction

actor Manager as "Quản lý" 
actor Staff as "Nhân viên" 

rectangle Product as "Sản phẩm" {
    usecase ProductCreate as "Thêm sản phẩm"
    usecase ProductSearch as "Tìm kiếm sản phẩm"
    usecase ProductSearchByName as "Tìm bằng tên"
    usecase ProductSearchByBarcode as "Tìm bằng mã hàng"
    usecase ProductSearchOrderByName as "Sắp xếp theo tên"
    usecase ProductSearchOrderByDateCreated as "Sắp xếp theo ngày tạo"
    usecase ProductView as "Xem sản phẩm"
    usecase ProductEdit as "Sửa sản phẩm"
    usecase ProductDelete as "Xóa sản phẩm"
}

Staff -- ProductSearch
Staff -- ProductView
Manager -- ProductSearch
Manager -- ProductView
Manager -- ProductCreate
Manager -- ProductEdit
Manager -- ProductDelete
ProductSearch <|-- ProductSearchByName
ProductSearch <|-- ProductSearchByBarcode
ProductSearch <|-- ProductSearchOrderByName
ProductSearch <|-- ProductSearchOrderByDateCreated
@enduml