@startuml ManageClient
left to right direction

actor :Người dùng: as User
actor :Quản lí: as Manager
actor :Nhân viên: as Staff

usecase ManageClient as "Quản lý khách hàng"
usecase CreateClient as "Thêm khách hàng"
usecase EditClient as "Sửa khách hàng"
usecase DeleteClient as "Xóa khách hàng"

Manager --|> User
Staff --|> User

User -- ManageClient
ManageClient ..> CreateClient : <<include>>
ManageClient <.. EditClient : <<extend>>
ManageClient <.. DeleteClient : <<extend>>
@enduml