@startuml Client
left to right direction

actor User as "Người dùng"
actor Manager as "Quản lý"
actor Employee as "Nhân viên"

rectangle Client as "Khách hàng" {
    usecase ClientSearch as "Tìm kiếm khách hàng"
    usecase ClientSearchByName as "Tìm bằng tên"
    usecase ClientSearchByPhonenumber as "Tìm bằng số điện thoại"

    usecase ClientFilter as "Lọc và xem khách hàng"
    
    usecase ClientManage as "Quản lý khách hàng"
    usecase ClientCreate as "Thêm khách hàng"
    usecase ClientEdit as "Sửa khách hàng"
    usecase ClientDelete as "Xóa khách hàng"
}

Employee -r-|> User
Manager -l-|> User

User -- ClientSearch
ClientSearch <|-- ClientSearchByName
ClientSearch <|-- ClientSearchByPhonenumber

User -- ClientFilter

User -- ClientManage
ClientManage <|-- ClientCreate
ClientManage <|-- ClientEdit
ClientManage <|-- ClientDelete
@enduml
