@startuml AuditReport
left to right direction

actor Manager as "Quản lý"

rectangle AuditReport as "Báo cáo kiểm kho" {
    usecase AuditReportSearch as "Tìm kiếm báo cáo"
    usecase AuditReportSearchByName as "Tìm bằng tên"
    usecase AuditReportSearchByBarcode as "Tìm bằng mã hàng"
    usecase AuditReportFilterStartDate as "Lọc từ ngày"
    usecase AuditReportFilterEndDate as "Lọc đến ngày"
    usecase AuditReportView as "Xem báo cáo"
    usecase AuditReportCreate as "Thêm báo cáo"
    usecase AuditReportDelete as "Xóa báo cáo"
    usecase ProductUpdateStock as "Cập nhật tồn kho sản phẩm"
}

Manager -- AuditReportSearch
Manager -- AuditReportView
Manager -- AuditReportCreate
Manager -- AuditReportDelete
AuditReportSearch <|-- AuditReportSearchByName
AuditReportSearch <|-- AuditReportSearchByBarcode
AuditReportSearch <|-- AuditReportFilterStartDate
AuditReportSearch <|-- AuditReportFilterEndDate
AuditReportCreate ..> ProductUpdateStock : <<include>>
@enduml