using Application.Exceptions;
using Application.Interfaces.Repositories;
using Domain.DTOs;
using Domain.DTOs.ExportReports;
using Domain.Entities;
using Domain.Mappers;

namespace Application.Services;
public class ExportReportService(
	IExportReportRepository exportReportRepository,
	IProductRepository productRepository,
	IUserRepository userRepository)
{
	public async Task<IEnumerable<ExportReportShort>> SearchAsync(
		string productNameOrBarcode,
		string authorName,
		TimeRange timeRange,
		OrderBy orderBy,
		Pagination pagination)
	{
		var entities = await exportReportRepository.SearchAsync(productNameOrBarcode, authorName, timeRange, orderBy, pagination);

		return entities.Select(ExportReportMapper.ToShort);
	}

	public async Task<uint> CountAsync(
		string productNameOrBarcode,
		string authorName,
		TimeRange timeRange,
		OrderBy orderBy)
	{
		var count = await exportReportRepository.CountAsync(productNameOrBarcode, authorName, timeRange, orderBy);

		return count;
	}

	public async Task<ExportReport?> GetAsync(string id)
	{
		return await exportReportRepository.GetAsync(id);
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="create"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="OutOfStockException"></exception>
	/// <exception cref="UnknownException"></exception>
	public async Task<string> CreateAsync(ExportReportCreate create)
	{
		var user = await userRepository.GetAsync(create.AuthorUserId)
			?? throw new InvalidIdException("UserId was not found.", [create.AuthorUserId]);
		var createIds = create.ProductItems.Select(x => x.Id).ToArray();
		var products = await productRepository.GetByIdsAsync(createIds);

		if (products.Count != create.ProductItems.Length)
		{
			var nonExistingIds = createIds.Except(products.Select(x => x.Id!));
			throw new InvalidIdException("ProductIds were not found.", nonExistingIds.ToArray());
		}

		var changes = products
			.Join(
				create.ProductItems,
				product => product.Id,
				create => create.Id,
				(product, create) => new
				{
					create.Id,
					product.Name,
					product.Barcode,
					product.InStock,
					create.Quantity
				})
			.ToArray();

		var outOfStockProductIds = changes
			.Where(x => x.InStock < x.Quantity)
			.Select(x => x.Id)
			.ToArray();
		if (outOfStockProductIds.Length > 0)
		{
			throw new OutOfStockException(outOfStockProductIds);
		}

		#region Creating entity
		var userInfo = UserMapper.ToInfo(user);
		var items = changes
			.Select(x => new ExportReportProductItem()
			{
				Id = x.Id,
				Name = x.Name,
				Barcode = x.Barcode,
				Quantity = x.Quantity
			})
			.ToList();
		var entity = new ExportReport()
		{
			Author = userInfo,
			ProductItems = items,
			DateCreated = DateTime.UtcNow,
			IsAutoGenerated = false
		};
		#endregion

		var tasks = changes
			.Select(x => productRepository.UpdateAsync(x.Id, x => x.InStock, x.InStock - x.Quantity))
			.Append(exportReportRepository.CreateAsync(entity));
		await Task.WhenAll(tasks);

		return entity.Id!;
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="id"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="UnknownException"></exception>
	public async Task DeleteAsync(string id)
	{
		await exportReportRepository.SoftDeleteAsync(id);
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="id"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="UnknownException"></exception>
	public async Task CancelAsync(string id)
	{
		var report = await exportReportRepository.GetAsync(id, x => x.DateCancelled == null)
			?? throw new InvalidIdException("Id was not found or cancelled or deleted.", [id]);

		var products = await productRepository.GetByIdsAsync(report.ProductItems.Select(x => x.Id));

		var tasks = products
			.Join(
				report.ProductItems,
				product => product.Id,
				report => report.Id,
				(product, report) => productRepository.UpdateAsync(report.Id, x => x.InStock, product.InStock + report.Quantity))
			.Append(exportReportRepository.UpdateAsync(id, x => x.DateCancelled, DateTime.UtcNow));

		await Task.WhenAll(tasks);
	}
}
