using Application.Exceptions;
using Application.Interfaces.Repositories;
using Domain.DTOs;
using Domain.DTOs.Invoices;
using Domain.Entities;
using Domain.Mappers;

namespace Application.Services;
public class InvoiceService(
	IInvoiceRepository invoiceRepository,
	IClientRepository clientRepository,
	IProductRepository productRepository,
	IExportReportRepository exportReportRepository,
	IUserRepository userRepository)
{
	public async Task<IEnumerable<InvoiceShort>> SearchAsync(
		string productNameOrBarcode,
		string clientNameOrPhonenumber,
		string authorName,
		InvoiceStatus status,
		TimeRange timeRange,
		OrderBy orderBy,
		Pagination pagination)
	{
		var entities = await invoiceRepository.SearchAsync(
			productNameOrBarcode,
			clientNameOrPhonenumber,
			authorName,
			status,
			timeRange,
			orderBy,
			pagination);

		return entities.Select(InvoiceMapper.ToShort);
	}

	public async Task<uint> CountAsync(
		string productNameOrBarcode,
		string clientNameOrPhonenumber,
		string authorName,
		InvoiceStatus status,
		TimeRange timeRange,
		OrderBy orderBy)
	{
		var count = await invoiceRepository.CountAsync(
			productNameOrBarcode,
			clientNameOrPhonenumber,
			authorName,
			status,
			timeRange,
			orderBy);

		return count;
	}

	public async Task<Invoice?> GetAsync(string id)
	{
		return await invoiceRepository.GetAsync(id);
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="create"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="OutOfStockException"></exception>
	public async Task<string> CreateAsync(InvoiceCreate create)
	{
		var user = await userRepository.GetAsync(create.AuthorUserId)
			?? throw new InvalidIdException("UserId was not found.", [create.AuthorUserId]);

		ClientInfo? clientInfo = null;
		if (create.ClientId is not null)
		{
			var client = await clientRepository.GetAsync(create.ClientId)
				?? throw new InvalidIdException("ClientId was not found.", [create.ClientId]);
			clientInfo = ClientMapper.ToInfo(client);
		}

		var createIds = create.ProductItems.Select(x => x.Id).ToArray();
		var products = await productRepository.GetByIdsAsync(createIds);

		if (products.Count != create.ProductItems.Length)
		{
			var nonExistingIds = createIds.Except(products.Select(x => x.Id!));
			throw new InvalidIdException("ProductIds were not found.", nonExistingIds.ToArray());
		}

		var changes = products
			.Join(
				create.ProductItems,
				product => product.Id,
				create => create.Id,
				(product, create) => new
				{
					Id = create.Id,
					Name = product.Name,
					Barcode = product.Barcode,
					InStock = product.InStock,
					SellingPrice = product.SellingPrice,
					Quantity = create.Quantity
				})
			.ToArray();

		var outOfStockProductIds = changes
			.Where(x => x.InStock < x.Quantity)
			.Select(x => x.Id)
			.ToArray();
		if (outOfStockProductIds.Length > 0)
		{
			throw new OutOfStockException(outOfStockProductIds);
		}

		var userInfo = UserMapper.ToInfo(user);
		var timeNow = DateTime.UtcNow;

		#region Creating export report
		var exportReportProductItems = changes
			.Select(x => new ExportReportProductItem()
			{
				Id = x.Id,
				Name = x.Name,
				Barcode = x.Barcode,
				Quantity = x.Quantity
			})
			.ToList();
		var exportReportEntity = new ExportReport()
		{
			Author = userInfo,
			ProductItems = exportReportProductItems,
			IsAutoGenerated = true,
			DateCreated = timeNow
		};
		await exportReportRepository.CreateAsync(exportReportEntity);
		#endregion

		#region Creating invoice
		var invoiceProductItems = changes
			.Select(x => new InvoiceProductItem()
			{
				Id = x.Id,
				Name = x.Name,
				Barcode = x.Barcode,
				Price = x.SellingPrice,
				Quantity = x.Quantity
			})
			.ToList();
		var invoiceEntity = new Invoice()
		{
			Author = userInfo,
			Client = clientInfo,
			ExportReportId = exportReportEntity.Id!,
			ProductItems = invoiceProductItems,
			GrandTotal = create.GrandTotal,
			DateCreated = timeNow,
			DatePaid = create.IsPaid ? timeNow : null,
		};
		#endregion

		var tasks = changes
			.Select(change => productRepository.UpdateAsync(change.Id, x => x.InStock, change.InStock - change.Quantity))
			.Append(invoiceRepository.CreateAsync(invoiceEntity));
		await Task.WhenAll(tasks);

		return invoiceEntity.Id!;
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="id"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="UnknownException"></exception>
	public async Task DeleteAsync(string id)
	{
		await invoiceRepository.SoftDeleteAsync(id);
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="id"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="UnknownException"></exception>
	public async Task CancelAsync(string id)
	{
		var invoice = await invoiceRepository.GetAsync(id, x => x.DateCancelled == null)
			?? throw new InvalidIdException("Id was not found or cancelled or deleted.", [id]);

		var products = await productRepository.GetByIdsAsync(invoice.ProductItems.Select(x => x.Id));

		var timeCancelled = DateTime.UtcNow;
		var tasks = products
			.Join(
				invoice.ProductItems,
				product => product.Id,
				invoiceProductItem => invoiceProductItem.Id,
				(product, invoiceProductItem) => productRepository.UpdateAsync(invoiceProductItem.Id, x => x.InStock, product.InStock + invoiceProductItem.Quantity))
			.Append(invoiceRepository.UpdateAsync(id, x => x.DateCancelled, timeCancelled));
		await Task.WhenAll(tasks);

		await exportReportRepository.UpdateAsync(invoice.ExportReportId, x => x.DateCancelled, timeCancelled);
	}

	/// <summary>
	/// 
	/// </summary>
	/// <param name="id"></param>
	/// <returns></returns>
	/// <exception cref="InvalidIdException"></exception>
	/// <exception cref="UnknownException"></exception>
	public async Task PayAsync(string id)
	{
		await invoiceRepository.UpdateAsync(
			id,
			x => x.DatePaid,
			DateTime.UtcNow,
			x => x.DatePaid == null && x.DateCancelled == null);
	}
}
