@startuml ImportReportPATCHCancelSequence
hide footbox

actor "Frontend" as Client
boundary "API Server" as Server
control ImportReportsController
participant ImportReportService
participant ImportReportRepository
database "Cơ sở dữ liệu" as Database

Client -> Server ++ : PATCH api/ImportReports/{id}/cancel
Server -> ImportReportsController ++ : Cancel(string id)
ImportReportsController --> ImportReportService ++ : Cancel(string id)
ImportReportService --> ImportReportRepository ++ : Update(string id, ...)
ImportReportRepository --> Database ++ : Sửa trạng thái\ncủa báo cáo
Database --> ImportReportRepository -- : Trả về kết quả
ImportReportRepository --> ImportReportService -- : return bool
ImportReportService --> ImportReportsController -- : return bool
ImportReportsController --> Server -- : return bool
Server --> Client -- : 204 OK

@enduml
