version: '3.8'
name: inventoice-dev

services:
  webapi:
    container_name: inventoice-dev-webapi
    image: inventoice-webapi:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MainMongoDB__ConnectionString=mongodb://inventoice-dev:Str0ngPa55w0rd@database:27017
      - MainMongoDB__DatabaseName=inventoice-dev
      - IdentityMongoDB__ConnectionString=mongodb://inventoice-dev:Str0ngPa55w0rd@database:27017
      - IdentityMongoDB__DatabaseName=inventoiceidentity-dev
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "21080:8080"

  database:
    container_name: inventoice-dev-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=inventoice-dev
      - MONGO_INITDB_ROOT_PASSWORD=Str0ngPa55w0rd
    ports:
      - "21081:27017"
    volumes:
      - inventoice-dev:/data/db

volumes:
  inventoice-dev:
    external: true
