version: '3.8'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoConnection__ConnectionString=mongodb://database:27017
    ports:
      - "21080:8080"
  database:
    ports:
      - "27017:27017"
    volumes:
      - ~/volumes/inventoice:/data/db
