version: '3.8'
name: inventoice-dev

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MainMongoDB__ConnectionString=mongodb://database:27017
      - MainMongoDB__DatabaseName=inventoice-dev
      - IdentityMongoDB__ConnectionString=mongodb://database:27017
      - IdentityMongoDB__DatabaseName=inventoiceidentity-dev
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "21080:8080"
  database:
    ports:
      - "27017:27017"
    volumes:
      - inventoice-dev:/data/db

volumes:
  inventoice-dev:
    external: true
