version: '3.8'
name: inventoice

services:
  webapi:
    container_name: inventoice-webapi
    restart: unless-stopped
    environment:
      - MongoConnection__ConnectionString=mongodb://database:27017
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "21080:8080"
  database:
    container_name: inventoice-database
    restart: unless-stopped
    ports:
      - "27017"
    volumes:
      - inventoice:/data/db

volumes:
  inventoice:
    external: true
